/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as EventsRouteImport } from './routes/events'
import { Route as BuildNotesRouteImport } from './routes/build-notes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventIdRouteImport } from './routes/event.$id'

const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildNotesRoute = BuildNotesRouteImport.update({
  id: '/build-notes',
  path: '/build-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build-notes': typeof BuildNotesRoute
  '/events': typeof EventsRoute
  '/methodology': typeof MethodologyRoute
  '/event/$id': typeof EventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build-notes': typeof BuildNotesRoute
  '/events': typeof EventsRoute
  '/methodology': typeof MethodologyRoute
  '/event/$id': typeof EventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build-notes': typeof BuildNotesRoute
  '/events': typeof EventsRoute
  '/methodology': typeof MethodologyRoute
  '/event/$id': typeof EventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/build-notes' | '/events' | '/methodology' | '/event/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/build-notes' | '/events' | '/methodology' | '/event/$id'
  id:
    | '__root__'
    | '/'
    | '/build-notes'
    | '/events'
    | '/methodology'
    | '/event/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildNotesRoute: typeof BuildNotesRoute
  EventsRoute: typeof EventsRoute
  MethodologyRoute: typeof MethodologyRoute
  EventIdRoute: typeof EventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-notes': {
      id: '/build-notes'
      path: '/build-notes'
      fullPath: '/build-notes'
      preLoaderRoute: typeof BuildNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildNotesRoute: BuildNotesRoute,
  EventsRoute: EventsRoute,
  MethodologyRoute: MethodologyRoute,
  EventIdRoute: EventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
